# which DAG to execute for each "hook" and what global_option_data namespace to use
hook_dag_map:
  ingress:
    dag_name: ingress
    global_option_data_key: ingress

  egress:
    dag_name: egress

# map of namespace -> option_data
# these are attached to hooks in the `hook_dag_map` and passed to a DAG
# during execution
global_option_data:
  ingress:
    # TODO: better example.. this is a bit of a stretch
    response_codes:
      success: 200
      notfound: 404

# what types of processing_nodes -- effectively a template
processing_node_types:
  1:
    processing_function_type: attribute_match
    inlets:
      0:
        name: '0th inlet'
    outlets:
      0:
        name: '0th outlet true'
        returns: [true]
      1:
        name: '1st outlet false'
        returns: [false]
  2:
    processing_function_type: execute_dynamic_dag
    inlets:
      0:
        name: '0th inlet'
    outlets:
      0:
        name: '0th outlet true'
        returns: [true]
  3:
    processing_function_type: set_attribute
    inlets:
      0:
        name: '0th inlet'
    outlets:
      0:
        name: '0th outlet true'
        returns: [true]
  4:
    name: 'set_status_code'
    info: 'set status code'
    processing_function_type: set_attribute
    arg_spec:
      value:
        type: int
        # key for all possible options, NOT a place to get the values from
        # for the node instance-- they live in the node instance as "args".
        # this means that the value you are passed will be a key to lookup in options
        global_option_data_key: response_codes
    inlets:
      0:
        name: '0th inlet'
    outlets:
      0:
        name: '0th outlet true'
        returns: [true]

# TODO: add options for max_depth, etc. for DAG validation and execution
# all the DAGs
dags:
  ingress:
    starting_node: [1, 0]
    # THIS is not layered
    processing_nodes:
      1: # node instance
        type_id: 1
        args:
          attribute: 'state.pristine_request.headers.Host'
          # list of the domains to match against
          values:
            - a.com
            - b.com
            - localhost:8888
        outlets:
          0: [2, 0]
          1: [3, 0]
      2: # node instance
        type_id: 2
        args:
          dag_prefix: dynamic_domain
          suffix_key: 'state.pristine_request.headers.Host'
      3:
        type_id: 3
        args:
          attribute: state.response.body
          value: "not found!"
        outlets:
          0: [4, 0]
      4:
        type_id: 4
        args:
          attribute: state.response.code
          value: notfound
  egress:
    starting_node: [1, 0]
    processing_nodes:
      1: # node instance
        type_id: 3
        args:
          attribute: 'state.response.headers.foo'
          value: 'bar'

  # per domain
  dynamic_domain_localhost:8888:
    starting_node: [1, 0]
    processing_nodes:
      1:
        type_id: 1
        args:
          attribute: 'state.pristine_request.path'
          values:
            - '/foo/bar'
            - '/foo'
        outlets:
          0: [2, 0]
          1: [4, 0]
      2:
        type_id: 3
        args:
          attribute: "state.response.body"
          value: "found!"
        outlets:
          0: [3, 0]
      3:
        type_id: 3
        args:
          attribute: "state.response.code"
          value: 200
      4:
        type_id: 3
        args:
          attribute: "state.request.headers.Host"
          value: "foo.com"
